In [3]:
from numpy import*
from cmath import*

# Basic gates
x=matrix([[0,1],[1,0]]) #pauli x gate
y=matrix([[0,-1j],[1j,0]])
z=matrix([[1,0],[0,-1]])
h=matrix([[1/sqrt(2),1/sqrt(2)],[1/sqrt(2),-1/sqrt(2)]])
s=matrix([[1,0],[0,1j]])
theta=complex(0,pi/4)
T=matrix([[1,0],[0,exp(theta)]])
cx=matrix([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
ccx=matrix([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0,],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
cz=matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,-1]])
swap=matrix([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
i=matrix([[1,0],[0,1]])
#one qubit state
ket_0=matrix([[1],[0]])
bra_0=transpose(ket_0)
ket_1=x*ket_0
bra_1=transpose(ket_1)
#2 qubit states
ket_00=kron(ket_0,ket_0)
ket_01=kron(ket_0,ket_1)
ket_10=kron(ket_1,ket_0)
ket_11=kron(ket_1,ket_1)
#special gates



In [7]:
u=kron(kron(i,i),cx)
print(u)
psi=kron(kron(kron(ket_0,ket_0),ket_1),ket_0)
print(psi)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [8]:
t=u*psi
print(t)

[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [9]:
kron(cx,x)

matrix([[0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0]])

In [4]:
I=matrix([[1,0],[0,1]])

In [5]:
kron(z,I)*kron(x,x)-kron(x,x)*kron(z,I)

matrix([[ 0,  0,  0,  2],
        [ 0,  0,  2,  0],
        [ 0, -2,  0,  0],
        [-2,  0,  0,  0]])